development: &development
  adapter: postgresql
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  database: <%= ENV.fetch("PG_DATABASE", "frontier_db") %>
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  pool: 5

production:
 <<: *development
