require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/bundle"

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/AbcSize:
  Enabled: false # TODO: enable